### ISSUE TITLE
0.12.5 webpack5 项目 build 后

### ISSUE THREAD

**Issue by The-End-Hero** [fuzhenn/maptalks-gl-layers#7]
![image](https://user-images.githubusercontent.com/19590233/185311254-96bf76f1-ba0e-412c-8ad7-94c99b986ccf.png)

**Comment by The-End-Hero** [comment]
退回 0.10.7后 恢复正常

**Comment by fuzhenn** [comment]
不知道新版本还是否正常，先关闭
