### ISSUE TITLE
Where are the source codes of dependencies?

### ISSUE THREAD

**Issue by exotfboy** [fuzhenn/maptalks-gl-layers#9]
The library contains the following plugins:
>@maptalks/gl
@maptalks/analysis
@maptalks/vt
@maptalks/gltf-layer
@maptalks/3dtiles
@maptalks/video-layer
@maptalks/transform-control
@maptalks/msd-json-loader

And provide example like this:
```
const vtLayer = new VectorTileLayer('vt', {
    urlTemplate: 'http://tile.maptalks.com/test/planet-single/{z}/{x}/{y}.mvt',
    spatialReference: 'preset-vt-3857'
});
```

Then I want to make it clear about the usage of the `VectorTileLayer` and then I tried to find the source codes of the dependencies while nothing found.

Did I miss anything?

**Comment by Frankiness** [comment]
need to ```import { VectorTileLayer } from '@maptalks/gl-layers';```

**Comment by exotfboy** [comment]
How about the source codes?

**Comment by Frankiness** [comment]
> 

not open source
